#  docker network create garagify-shared-network;docker compose up;
version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SERVICE_DB_URL=${SERVICE_DB_URL}
      - SERVICE_DB_LOGIN=${SERVICE_DB_LOGIN}
      - SERVICE_DB_PASSWORD=${SERVICE_DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_SMTP_AUTH=${MAIL_SMTP_AUTH}
      - MAIL_SMTP_STARTTLS_ENABLE=${MAIL_SMTP_STARTTLS_ENABLE}
      - MAIL_SMTP_FROM=${MAIL_SMTP_FROM}
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - garagify-shared-network

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ${SERVICE_DB_LOGIN}
      POSTGRES_PASSWORD: ${SERVICE_DB_PASSWORD}
      POSTGRES_DB: ${SERVICE_DB_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - garagify-shared-network

networks:
  garagify-shared-network:
    external: true

volumes:
  postgres-data:
