spring:
  application:
    name: garagify
  datasource:
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  docker:
    compose:
      enabled: false

server:
  port: 8080

logging:
  level:
    org.springframework.web: DEBUG
    root: INFO

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
