openapi: 3.0.3
info:
  title: Garagify
  version: 1.0.0
  description: API

tags:
  - name: AuthController
    description: Handles Google token authentication and JWT refresh operations
  - name: ParkingSpotsController
paths:
  /api/v1/auth/access:
    post:
      tags:
        - AuthController
      summary: Authenticate using a Google token
      operationId: authenticateWithGoogle
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenVerificationForm'
      responses:
        '200':
          description: JWT tokens returned
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenDto'

  /api/v1/auth/refresh:
    post:
      tags:
        - AuthController
      summary: Refresh JWT token
      operationId: refreshToken
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenVerificationForm'
      responses:
        '200':
          description: New JWT tokens returned
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenDto'




  /parking-spots:
    get:
      summary: This is summary
      tags:
        - ParkingSpotsController
      description: This is a description
      operationId: getAllParkingSpots
      responses:
        200:
          description: This means its ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ParkingSpot'

  /user/by-spot-id/{spot_id}:
    get:
      summary: This is summary
      tags:
        - ParkingSpotsController
      description: This is a description
      operationId: getUserBySpotId
      parameters:
        - name: spot_id
          in: path
          required: true
          description: The id of the parking spot
          schema:
            type: string
      responses:
        200:
          description: This means its ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'


components:
  schemas:
    TokenVerificationForm:
      type: object
      properties:
        token:
          type: string
      required:
        - token

    TokenDto:
      type: object
      properties:
        access:
          type: string
        refresh:
          type: string
      required:
        - access
        - refresh


    ParkingSpot:
      description: This is the parking spot model
      type: object
      properties:
        name:
          description: The name of parking spot
          type: string
        id:
          description: Id of parking spot
          type: string
        x:
          description: X coordinate of parking spot
          type: number
        y:
          description: Y coordinate of parking spot
          type: number
        id_owner:
          description: Id of owner
          type: string

    User:
      description: This is the user model
      type: object
      properties:
        name:
          description: The name of user
          type: string
        id:
          description: Id of user
          type: string
        email:
          description: Email of user
          type: string
        profile_picture_url:
          description: Profile picture url of user
          type: string
